name: Download Artifact

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID of the previous workflow'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: shared-file-${{ github.event.inputs.run_id }}

    - name: Display shared file
      run: cat shared-file-${{ github.event.inputs.run_id }}.txt