name: Run Track Stars

on:
  schedule:
    - cron: '*/1 * * * *'  # 每分钟运行一次
  workflow_dispatch:

jobs:
  track-stargazers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 python-dotenv  # 添加 python-dotenv

    - name: Download previous stargazers file
      uses: actions/download-artifact@v3
      with:
        name: stargazers
        path: stargazers.json
      continue-on-error: true  # 如果文件不存在，不要失败

    - name: Track Stargazers
      env:
        REPO_OWNER: ${{ secrets.REPO_OWNER }}
        REPO_NAME: ${{ secrets.REPO_NAME }}
      run: python star.py  # 替换为你的脚本文件名

    - name: Upload stargazers file
      uses: actions/upload-artifact@v3
      with:
        name: stargazers
        path: stargazers.json

  use-stargazers:
    runs-on: ubuntu-latest
    needs: track-stargazers

    steps:
    - name: Download stargazers file
      uses: actions/download-artifact@v3
      with:
        name: stargazers

    - name: Use the stargazers data
      run: cat stargazers.json