name: Run Track Stars

on:
  # schedule:
  #   - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:

jobs:
  track-stargazers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 python-dotenv  # 添加 python-dotenv

    - name: Get previous run ID
      id: get_previous_run_id
      env:
        MY_GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        echo "Repository: ${{ github.repository }}"
        response=$(curl -s -H "Authorization: token $MY_GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs?status=success&per_page=1")
        echo "API Response: $response"
        previous_run_id=$(echo $response | jq -r '.workflow_runs[0].id')
        echo "PREV_RUN_ID=$previous_run_id" >> $GITHUB_ENV

    - name: Download previous stargazers file
      uses: actions/download-artifact@v3
      with:
        name: stargazers-${{ env.PREV_RUN_ID }}
        path: stargazers.json
      continue-on-error: true  # 如果文件不存在，不要失败

    - name: List files for debugging
      if: always()
      run: ls -l  # 列出当前目录的文件，帮助调试

    - name: Track Stargazers
      env:
        REPO_OWNER: ${{ secrets.REPO_OWNER }}
        REPO_NAME: ${{ secrets.REPO_NAME }}
      run: python star.py  # 替换为你的脚本文件名

    - name: Upload stargazers file
      uses: actions/upload-artifact@v3
      with:
        name: stargazers-${{ github.run_id }}
        path: stargazers.json

  use-stargazers:
    runs-on: ubuntu-latest
    needs: track-stargazers

    steps:
    - name: Download stargazers file
      uses: actions/download-artifact@v3
      with:
        name: stargazers-${{ needs.track-stargazers.outputs.PREV_RUN_ID }}
      continue-on-error: true  # 如果文件不存在，不要失败

    - name: List files for debugging
      if: always()
      run: ls -l  # 列出当前目录的文件，帮助调试

    - name: Use the stargazers data
      run: cat stargazers.json