name: Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a file to share
      run: echo "This is a shared file" > shared-file-${{ github.run_id }}.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: shared-file-${{ github.run_id }}
        path: shared-file-${{ github.run_id }}.txt